const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Root cause:
// RCT-Folly.podspec has explicit per-subdirectory source_file globs
// (folly/*.h, folly/lang/*.h, …) but NO folly/coro/*.h entry.
// So Pods/RCT-Folly/ never receives the coro/ directory.
// React Native new-arch and Reanimated both include folly/coro/ headers
// from $(PODS_ROOT)/RCT-Folly, which resolves to the empty coro/ dir.
//
// Shim strategy:
// 1. Write ios/FollyHeaders/folly/coro/coroutine.h with the full
//    folly::coro namespace (not just folly::) so Swift C++ interop
//    can resolve "folly.Coro" (Swift capitalises C++ namespace names).
// 2. Append ios/FollyHeaders to HEADER_SEARCH_PATHS on every pod target
//    so every target falls back to our shim when the real file is absent.
// 3. Also append $(PODS_ROOT)/RCT-Folly so any other folly/ headers
//    that DID land in the pod are reachable after our shim.
// 4. Keep CLANG_CXX_LANGUAGE_STANDARD = c++20 (belt-and-suspenders;
//    react_native_post_install does this too, but only for pod targets,
//    not xcconfig files that Xcode generates for embedded frameworks).

// ─── Header shim content ────────────────────────────────────────────────────
// Mirrors the public surface of Folly's folly/coro/coroutine.h:
//   - Basic coroutine primitives in namespace folly  (backward compat)
//   - The folly::coro sub-namespace with the same primitives
//   - A minimal coroutine-capable folly::coro::Coro<T> type so that
//     generated React Native codegen headers can use it as a return type
const FOLLY_CORO_H = `\
#pragma once
// folly/coro/coroutine.h — compatibility shim
// Auto-generated by plugins/withIosCppFlags.js
// Provides the folly::coro namespace required by React Native new-arch.

#if __has_include(<coroutine>)
#  include <coroutine>

namespace folly {

  // ── Primitives in folly:: (original Folly interface) ──────────────────────
  template <typename Promise = void>
  using coro_handle = std::coroutine_handle<Promise>;
  using suspend_always = std::suspend_always;
  using suspend_never  = std::suspend_never;
  inline std::coroutine_handle<> noop_coroutine() noexcept {
    return std::noop_coroutine();
  }

  // ── folly::coro namespace ─────────────────────────────────────────────────
  // Swift C++ interop imports this namespace as "Coro" (UpperCamelCase).
  // It must exist for folly.Coro.* access to resolve in Swift callers.
  namespace coro {

    template <typename Promise = void>
    using coroutine_handle = std::coroutine_handle<Promise>;
    using suspend_always = std::suspend_always;
    using suspend_never  = std::suspend_never;
    inline std::coroutine_handle<> noop_coroutine() noexcept {
      return std::noop_coroutine();
    }

    // Minimal coroutine task type usable as a C++20 coroutine return type.
    // React Native codegen uses this as the return type of async module
    // methods; it does not need to be await-able at the shim level.
    template <typename T = void>
    class Coro {
    public:
      struct promise_type {
        Coro get_return_object() noexcept { return {}; }
        std::suspend_always initial_suspend() noexcept { return {}; }
        std::suspend_always final_suspend()   noexcept { return {}; }
        void return_void() noexcept {}
        void unhandled_exception() noexcept { std::terminate(); }
      };
    };

    // Specialisation for non-void T (stores a value).
    template <typename T>
    class Coro<T> {
    public:
      struct promise_type {
        Coro get_return_object() noexcept { return {}; }
        std::suspend_always initial_suspend() noexcept { return {}; }
        std::suspend_always final_suspend()   noexcept { return {}; }
        void return_value(T) noexcept {}
        void unhandled_exception() noexcept { std::terminate(); }
      };
    };

  } // namespace coro

  // folly::Coro<T> as a direct alias for folly::coro::Coro<T>
  template <typename T = void>
  using Coro = coro::Coro<T>;

} // namespace folly

#elif __has_include(<experimental/coroutine>)
#  include <experimental/coroutine>

namespace folly {
  template <typename Promise = void>
  using coro_handle = std::experimental::coroutine_handle<Promise>;
  using suspend_always = std::experimental::suspend_always;
  using suspend_never  = std::experimental::suspend_never;

  namespace coro {
    template <typename Promise = void>
    using coroutine_handle = std::experimental::coroutine_handle<Promise>;
    using suspend_always = std::experimental::suspend_always;
    using suspend_never  = std::experimental::suspend_never;

    template <typename T = void>
    class Coro {
    public:
      struct promise_type {
        Coro get_return_object() noexcept { return {}; }
        std::experimental::suspend_always initial_suspend() noexcept { return {}; }
        std::experimental::suspend_always final_suspend()   noexcept { return {}; }
        void return_void() noexcept {}
        void unhandled_exception() noexcept { std::terminate(); }
      };
    };

    template <typename T>
    class Coro<T> {
    public:
      struct promise_type {
        Coro get_return_object() noexcept { return {}; }
        std::experimental::suspend_always initial_suspend() noexcept { return {}; }
        std::experimental::suspend_always final_suspend()   noexcept { return {}; }
        void return_value(T) noexcept {}
        void unhandled_exception() noexcept { std::terminate(); }
      };
    };
  } // namespace coro

  template <typename T = void>
  using Coro = coro::Coro<T>;
} // namespace folly

#else
#  error "C++20 coroutine support required. Compile with -std=c++20."
#endif
`;

// ─── Podfile patch ───────────────────────────────────────────────────────────
const PATCH_MARKER = '# [withIosCppFlags-v3]';

function findCallEnd(src, start) {
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    if (src[i] === '(') depth++;
    else if (src[i] === ')') { if (--depth === 0) return i; }
  }
  return -1;
}

function patchPodfile(contents) {
  if (contents.includes(PATCH_MARKER)) return contents;

  // __dir__ in the Podfile expands to ios/ at pod-install time on any machine,
  // so the absolute path to FollyHeaders/ is always correct (local + EAS).
  const patch = `
  ${PATCH_MARKER}
  _folly_shim = File.join(__dir__, 'FollyHeaders')
  _rct_folly  = '$(PODS_ROOT)/RCT-Folly'
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |bc|
      bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      sp = bc.build_settings['HEADER_SEARCH_PATHS']
      sp = sp.is_a?(Array) ? sp.dup : (sp ? [sp] : ['$(inherited)'])
      sp += [_folly_shim] unless sp.join.include?('FollyHeaders')
      sp += [_rct_folly]  unless sp.join.include?('RCT-Folly')
      bc.build_settings['HEADER_SEARCH_PATHS'] = sp
    end
  end
`;

  const key = 'react_native_post_install(';
  const ki = contents.indexOf(key);
  if (ki !== -1) {
    const end = findCallEnd(contents, ki + key.length - 1);
    if (end !== -1)
      return contents.slice(0, end + 1) + '\n' + patch + contents.slice(end + 1);
  }

  const piKey = 'post_install do |installer|';
  if (contents.includes(piKey))
    return contents.replace(piKey, piKey + '\n' + patch);

  return contents + `\npost_install do |installer|\n${patch}\nend\n`;
}

// ─── Plugin ──────────────────────────────────────────────────────────────────
module.exports = function withIosCppFlags(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const iosDir = config.modRequest.platformProjectRoot;

      // Write the shim header tree: ios/FollyHeaders/folly/coro/coroutine.h
      const shimDir = path.join(iosDir, 'FollyHeaders', 'folly', 'coro');
      fs.mkdirSync(shimDir, { recursive: true });
      fs.writeFileSync(path.join(shimDir, 'coroutine.h'), FOLLY_CORO_H);

      // Patch the generated Podfile
      const podfilePath = path.join(iosDir, 'Podfile');
      if (!fs.existsSync(podfilePath)) return config;
      const original = fs.readFileSync(podfilePath, 'utf8');
      const patched = patchPodfile(original);
      if (patched !== original) fs.writeFileSync(podfilePath, patched);

      return config;
    },
  ]);
};
