const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// The real folly/coro/coroutine.h is part of the RCT-Folly pod but the pod
// spec does not expose the coro/ subdirectory as a public header, so it is
// absent from the built Pods/Headers tree that Clang actually searches.
// Setting CLANG_CXX_LANGUAGE_STANDARD alone does nothing when the file is
// physically missing.  We ship our own complete shim and point every pod
// target's HEADER_SEARCH_PATHS at it.
//
// Shim content mirrors the essential Folly surface that React Native new-arch
// code actually uses: the coro_handle/suspend type aliases in namespace folly.

const FOLLY_CORO_H = `\
#pragma once
// folly/coro/coroutine.h — compatibility shim
// Auto-generated by plugins/withIosCppFlags.js
// Provides the folly-namespace coroutine type aliases used by React Native
// new architecture without depending on other Folly internals.
#if __has_include(<coroutine>)
#  include <coroutine>
namespace folly {
  template <typename Promise = void>
  using coro_handle  = std::coroutine_handle<Promise>;
  using suspend_always = std::suspend_always;
  using suspend_never  = std::suspend_never;
  inline std::coroutine_handle<> noop_coroutine() noexcept {
    return std::noop_coroutine();
  }
} // namespace folly
#elif __has_include(<experimental/coroutine>)
#  include <experimental/coroutine>
namespace folly {
  template <typename Promise = void>
  using coro_handle  = std::experimental::coroutine_handle<Promise>;
  using suspend_always = std::experimental::suspend_always;
  using suspend_never  = std::experimental::suspend_never;
} // namespace folly
#else
#  error "C++20 coroutine support required. Pass -std=c++20 to the compiler."
#endif
`;

// Marker written into the Podfile so the patch is idempotent across
// repeated `expo prebuild` runs without --clean.
const PATCH_MARKER = '# [withIosCppFlags-v2]';

function findCallEnd(src, start) {
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    if (src[i] === '(') depth++;
    else if (src[i] === ')') { if (--depth === 0) return i; }
  }
  return -1;
}

function patchPodfile(contents) {
  // Idempotent: skip if already patched by this version of the plugin.
  if (contents.includes(PATCH_MARKER)) return contents;

  // In the Podfile __dir__ expands to the ios/ directory at runtime on
  // whatever machine runs `pod install` (local or EAS cloud worker).
  // We place FollyHeaders/ inside ios/ so the path is always valid.
  const patch = `
  ${PATCH_MARKER}
  _folly_shim = File.join(__dir__, 'FollyHeaders')
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |bc|
      bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      sp = bc.build_settings['HEADER_SEARCH_PATHS']
      sp = sp.is_a?(Array) ? sp.dup : (sp ? [sp] : ['$(inherited)'])
      bc.build_settings['HEADER_SEARCH_PATHS'] = sp + [_folly_shim] unless sp.join.include?('FollyHeaders')
    end
  end
`;

  // Preferred injection point: right after react_native_post_install(...)
  const key = 'react_native_post_install(';
  const ki = contents.indexOf(key);
  if (ki !== -1) {
    const end = findCallEnd(contents, ki + key.length - 1);
    if (end !== -1) {
      return contents.slice(0, end + 1) + '\n' + patch + contents.slice(end + 1);
    }
  }

  // Fallback: top of post_install block
  const piKey = 'post_install do |installer|';
  if (contents.includes(piKey)) {
    return contents.replace(piKey, piKey + '\n' + patch);
  }

  // Last resort: append a new block
  return contents + `\npost_install do |installer|\n${patch}\nend\n`;
}

module.exports = function withIosCppFlags(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const iosDir = config.modRequest.platformProjectRoot;

      // 1. Write the shim header so the file physically exists.
      //    ios/FollyHeaders/folly/coro/coroutine.h
      const shimDir = path.join(iosDir, 'FollyHeaders', 'folly', 'coro');
      fs.mkdirSync(shimDir, { recursive: true });
      fs.writeFileSync(path.join(shimDir, 'coroutine.h'), FOLLY_CORO_H);

      // 2. Patch the Podfile to add the shim to every pod target's
      //    HEADER_SEARCH_PATHS and force C++20 on the compiler.
      const podfilePath = path.join(iosDir, 'Podfile');
      if (!fs.existsSync(podfilePath)) return config;

      const original = fs.readFileSync(podfilePath, 'utf8');
      const patched = patchPodfile(original);
      if (patched !== original) fs.writeFileSync(podfilePath, patched);

      return config;
    },
  ]);
};
